### PR TITLE
[16.0] [MIG] stock_available_immediately

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Comment by marielejeune** [comment]
Depends on https://github.com/OCA/stock-logistics-availability/pull/2

**Review by lmignon — APPROVED** [review]
Thank you @marielejeune LGTM. Tested with #2 (Code review + functional tests)

**Comment by lmignon** [comment]
This one is to be merged with #2

**Comment by rousseldenis** [comment]
@marielejeune Could you rebase ?

**Review by marylla — APPROVED** [review]
I made a functional review. Looks good to me. :+1: 

Incoming deliveries that are not yet done are not included in "available to promise" quantity.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
