### PR TITLE
[17.0][MIG] stock_free_quantity: Migration to 17.0

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by jcadhoc** [comment]
@rousseldenis Thank you for review! Can you merge? Or there is something pending?

**Comment by jcadhoc** [comment]
@rousseldenis Hi Denis, do yo know why runboat is pending?

**Comment by rousseldenis** [comment]
> @rousseldenis Hi Denis, do yo know why runboat is pending?

I think this is because runboat was not on air when this was pushed. A rebase can solve it

**Comment by rousseldenis** [comment]
> @rousseldenis Thank you for review! Can you merge? Or there is something pending?

Usually, more than one review is required. Attract people here to review

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review, working ok.

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Comment by CasVissers-360ERP** [comment]
@rousseldenis Think it can be merged now (3 reviews including yours)

**Comment by rousseldenis** [comment]
@jcadhoc Could you fix pre-commit ?

**Comment by jcadhoc** [comment]
@rousseldenis Ready!

Sorry for the delay

**Comment by jcadhoc** [comment]
@rousseldenis Hi Denis!

This pr is ok for merge?

I want to migrate it to 18 so better if we can merge this first

**Review by florenciafrigieri2 — APPROVED** [review]
Functional test. Working ok. Free qty is ok within the product and in the product list.

**Comment by rousseldenis** [comment]
@jcadhoc Could you  squash your last pre-commit fix with the other one ? Thanks

**Comment by jcadhoc** [comment]
@rousseldenis squashed!

Thank you.

**Pull request merged**
