### PR TITLE
[MIG] sale_stock_available_info_popup: Migration to 16.0

### PR DESCRIPTION
**Pull request by bvanjeelharia**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@bvanjeelharia Thanks for this. Could you add module name in this commit?

image

**Comment by bvanjeelharia** [comment]
Hello Dennis,

The commit message was updated

Thanks and Regards,
[image: Logo] <https://www.brainvire.com/> [image: Logo]
Anjeel Haria
Software Engineer
M: +91 00000 00000
P: +91-22-61163300 / *EXTN:* 100
E: ***@***.***
W: www.brainvire.com
[image: Facebook icon] <https://www.facebook.com/Brainvire> [image:
LinkedIn icon] <https://www.linkedin.com/company/brainvire-infotech-inc/>
[image:
Twitter icon] <https://twitter.com/Brainvire> [image: Blog]
<https://www.brainvire.com/blog/?utm_source=email-signature>
[image: Company of the Year]
<https://www.brainvire.com/brainvire-recognized-as-company-of-the-year/>
[image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#review-491817> [image:
Reviewed on clutch]
<https://clutch.co/profile/brainvire-infotech#reviews> [image:
Digital Best Commerce Development Company]
<https://www.brainvire.com/recognized-as-best-ecommerce-development-company/>
[image:
Good Firms Top Web Developers]
<https://www.goodfirms.co/companies/view/1512/brainvire-infotech-inc>

Disclaimer: The information transmitted by this email is intended only for
the person or entity to which it is addressed. This email may contain
proprietary, business-confidential and/or privileged material. Please
consider the environment before printing.

**Review by rousseldenis — APPROVED** [review]
Code and functional review. Works as expected

**Comment by pedrobaeza** [comment]
I see now that the problem you had is the move of repo, so you need it to define 2 remotes in git and change the command to put one and the other. But good that you were able to solve it. Another badge in your git-fu!

Please squash your migration commits and don't do the second version change, as the changes you are doing is for this to work on v16, with no yet released version.

**Pull request closed without merging**
